### ISSUE TITLE
How much memory need?

### ISSUE THREAD

**Issue by stdex** [cr0hn/ktcal2#1]
How much memory need to brute with config -N -c -C --max-length 6 --min-length 6 ?
![image](https://cloud.githubusercontent.com/assets/4608879/15456509/dce385b4-207a-11e6-99d2-d5ea0a78f2c1.png)

**Comment by cr0hn** [comment]
Thank for the issue. 

I just rewritten the some part of code to fix this issue. Now, in my computer, only take +-20MB of RAM to run.

You can update ktcal2 doing:

``` bash
pip install -U ktcal2
```

![kt-cal2](https://cloud.githubusercontent.com/assets/4076390/17770029/ed0e452c-653b-11e6-8904-139ab1036d9f.jpg)
